structure(list(url = "pc/name/no_hit/property/InChIKey/JSON", 
    status_code = 404L, headers = structure(list(date = "Tue, 10 Oct 2023 11:49:18 GMT", 
        server = "Apache", `strict-transport-security` = "max-age=31536000; includeSubDomains; preload", 
        `referrer-policy` = "origin-when-cross-origin", `content-security-policy` = "upgrade-insecure-requests", 
        `cache-control` = "private", expires = "Tue, 10 Oct 2023 19:49:18 GMT", 
        `ncbi-phid` = "95B6E22D5253A3E10000000000000001.m_1", 
        `ncbi-sid` = "95B6E22D5253A3E1_0000SID", `x-throttling-control` = "Request Count status: Green (0%), Request Time status: Green (0%), Service status: Green (17%)", 
        `content-type` = "application/json", `set-cookie` = "ncbi_sid=95B6E22D5253A3E1_0000SID; domain=.nih.gov; path=/; expires=Thu, 10 Oct 2024 11:49:18 GMT", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `x-ua-compatible` = "IE=Edge", `x-xss-protection` = "1; mode=block", 
        `access-control-allow-origin` = "*", `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 10 Oct 2023 11:49:18 GMT", 
            server = "Apache", `strict-transport-security` = "max-age=31536000; includeSubDomains; preload", 
            `referrer-policy` = "origin-when-cross-origin", `content-security-policy` = "upgrade-insecure-requests", 
            `cache-control` = "private", expires = "Tue, 10 Oct 2023 19:49:18 GMT", 
            `ncbi-phid` = "95B6E22D5253A3E10000000000000001.m_1", 
            `ncbi-sid` = "95B6E22D5253A3E1_0000SID", `x-throttling-control` = "Request Count status: Green (0%), Request Time status: Green (0%), Service status: Green (17%)", 
            `content-type` = "application/json", `set-cookie` = "ncbi_sid=95B6E22D5253A3E1_0000SID; domain=.nih.gov; path=/; expires=Thu, 10 Oct 2024 11:49:18 GMT", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `x-ua-compatible` = "IE=Edge", `x-xss-protection` = "1; mode=block", 
            `access-control-allow-origin` = "*", `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = ".nih.gov", 
        flag = TRUE, path = "/", secure = FALSE, expiration = structure(1728560958, class = c("POSIXct", 
        "POSIXt")), name = "ncbi_sid", value = "95B6E22D5253A3E1_0000SID"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\n  \"Fault\": {\n    \"Code\": \"PUGREST.NotFound\",\n    \"Message\": \"No CID found\",\n    \"Details\": [\n      \"No CID found that matches the given name\"\n    ]\n  }\n}\n"), 
    date = structure(1696938558, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.002641, 
    connect = 0.107713, pretransfer = 0.322255, starttransfer = 0.44192, 
    total = 0.443548)), class = "response")
